server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 核心修复配置：找不到路由时全部交给 index.html
        try_files $uri $uri/ /index.html;
    }

    # 如果前端镜像里顺便配置了代理，请保留，没有就不用管
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}